# Generated by Django 5.1.1 on 2025-10-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
